# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b434da2f210b168ec280e523e1f0392"
name = "frontend"
handle = "frontend-21"
application_url = "https://enables-technical-usb-applied.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://enables-technical-usb-applied.trycloudflare.com/auth/callback",
  "https://enables-technical-usb-applied.trycloudflare.com/auth/shopify/callback",
  "https://enables-technical-usb-applied.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "hungstore-vn.myshopify.com"
automatically_update_urls_on_dev = true
